### ISSUE TITLE
lookup documentation?

### ISSUE THREAD

**Issue by systemkrash** [BoLaMN/loopback-mongo-aggregate-mixin#2]
When i use loopback explorer and put this in the filter

{"aggregate": {"lookup": {"from": "UserAccount", "localField": "userId", "foreign": "_id", "as": "userAccount"}}}

an error occurs

TypeError: Cannot read property 'map' of undefined
    at C:\development\wms\api\node_modules\loopback-mongo-aggregate-mixin\dist\aggregate.js:54:32
    at handleCallback (C:\development\wms\api\node_modules\mongodb\lib\utils.js:96:12)
    at C:\development\wms\api\node_modules\mongodb\lib\cursor.js:836:22
    at handleCallback (C:\development\wms\api\node_modules\mongodb-core\lib\cursor.js:159:5)
    at C:\development\wms\api\node_modules\mongodb-core\lib\cursor.js:577:22
    at queryCallback (C:\development\wms\api\node_modules\mongodb-core\lib\cursor.js:200:16)
    at Callbacks.emit (C:\development\wms\api\node_modules\mongodb-core\lib\topologies\server.js:119:3)
    at Connection.messageHandler (C:\development\wms\api\node_modules\mongodb-core\lib\topologies\server.js:397:23)
    at Socket.<anonymous> (C:\development\wms\api\node_modules\mongodb-core\lib\connection\connection.js:302:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

How to correctly use lookup in aggregate?

**Comment by systemkrash** [comment]
i got it. i forgot to append "Field" in foreignField. Sorry for the trouble.
